project:
  type: website
  output-dir: docs

website:
  title: "OA Barometer"
  favicon: "images/open_science_icon.png"
  navbar:
    background: "#424242"
    foreground: "#FFFF"
    title: false
    logo: "/images/open_science_title_logo_02.png"
    logo-href: "https://openscience.no"
    left:
      - href: index.qmd
        text: "OA Barometer"
  page-footer:
    border: true
    background: "#424242"
    left: |
      [![](/images/Sikt-Secondarylogo-NB-light.png){fig-alt="Sikt" width=170px}](https://sikt.no)
  open-graph: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
editor: visual

